name: phys201
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - libpython
  - jupyterlab
  - pymc=5.0.1
  - m2w64-toolchain
  - emcee=2.2.1
  - seaborn
  - python-graphviz
  - mkl-service
